--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize(cc.size(1280.0000, 720.0000))

--Create layout_bg
local layout_bg = ccui.ImageView:create()
layout_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
layout_bg:loadTexture("ToolbarBg.png",1)
layout_bg:setScale9Enabled(true)
layout_bg:setCapInsets(cc.rect(5,5,6,38))
layout_bg:setLayoutComponentEnabled(true)
layout_bg:setName("layout_bg")
layout_bg:setTag(12)
layout_bg:setCascadeColorEnabled(true)
layout_bg:setCascadeOpacityEnabled(true)
layout_bg:setAnchorPoint(0.0000, 0.5000)
layout_bg:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(layout_bg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0667)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1333)
layout:setSize(cc.size(1280.0000, 96.0000))
layout:setHorizontalEdge(2)
layout:setVerticalEdge(1)
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(624.0000)
layout:setBottomMargin(0.0000)
Layer:addChild(layout_bg)

--Create dragMap
local dragMap = ccui.Button:create()
dragMap:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
dragMap:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
dragMap:loadTexturePressed("DragMapButtonSelected.png",1)
dragMap:loadTextureDisabled("Default/Button_Disable.png",0)
dragMap:setTitleFontSize(14)
dragMap:setTitleColor(cc.c3b(65, 65, 70))
dragMap:setScale9Enabled(true)
dragMap:setCapInsets(cc.rect(5,5,30,30))
dragMap:setLayoutComponentEnabled(true)
dragMap:setName("dragMap")
dragMap:setTag(28)
dragMap:setCascadeColorEnabled(true)
dragMap:setCascadeOpacityEnabled(true)
dragMap:setPosition(48.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(dragMap)
layout:setPositionPercentX(0.0375)
layout:setPositionPercentY(0.0667)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(16.0000)
layout:setRightMargin(1200.0000)
layout:setTopMargin(640.0000)
layout:setBottomMargin(16.0000)
Layer:addChild(dragMap)

--Create Button_3_0
local Button_3_0 = ccui.Button:create()
Button_3_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0:loadTextureNormal("SaveMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0:setTitleFontSize(14)
Button_3_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0:setScale9Enabled(true)
Button_3_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0:setLayoutComponentEnabled(true)
Button_3_0:setName("Button_3_0")
Button_3_0:setTag(30)
Button_3_0:setCascadeColorEnabled(true)
Button_3_0:setCascadeOpacityEnabled(true)
Button_3_0:setPosition(121.4474, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0)
layout:setPositionPercentX(0.0949)
layout:setPositionPercentY(0.0667)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(89.4474)
layout:setRightMargin(1126.5530)
layout:setTopMargin(640.0000)
layout:setBottomMargin(16.0000)
Layer:addChild(Button_3_0)

--Create Button_3_0_0
local Button_3_0_0 = ccui.Button:create()
Button_3_0_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0_0:setTitleFontSize(14)
Button_3_0_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0_0:setScale9Enabled(true)
Button_3_0_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0_0:setLayoutComponentEnabled(true)
Button_3_0_0:setName("Button_3_0_0")
Button_3_0_0:setTag(31)
Button_3_0_0:setCascadeColorEnabled(true)
Button_3_0_0:setCascadeOpacityEnabled(true)
Button_3_0_0:setPosition(200.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0_0)
layout:setPositionPercentX(0.1563)
layout:setPositionPercentY(0.0667)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(168.0000)
layout:setRightMargin(1048.0000)
layout:setTopMargin(640.0000)
layout:setBottomMargin(16.0000)
Layer:addChild(Button_3_0_0)

--Create Button_3_0_0_0
local Button_3_0_0_0 = ccui.Button:create()
Button_3_0_0_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0_0_0:setTitleFontSize(14)
Button_3_0_0_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0_0_0:setScale9Enabled(true)
Button_3_0_0_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0_0_0:setLayoutComponentEnabled(true)
Button_3_0_0_0:setName("Button_3_0_0_0")
Button_3_0_0_0:setTag(38)
Button_3_0_0_0:setCascadeColorEnabled(true)
Button_3_0_0_0:setCascadeOpacityEnabled(true)
Button_3_0_0_0:setPosition(282.7406, 45.1549)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0_0_0)
layout:setPositionPercentX(0.2209)
layout:setPositionPercentY(0.0627)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(250.7406)
layout:setRightMargin(965.2594)
layout:setTopMargin(642.8451)
layout:setBottomMargin(13.1549)
Layer:addChild(Button_3_0_0_0)

--Create Button_3_0_0_0_0
local Button_3_0_0_0_0 = ccui.Button:create()
Button_3_0_0_0_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0_0_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0_0_0_0:setTitleFontSize(14)
Button_3_0_0_0_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0_0_0_0:setScale9Enabled(true)
Button_3_0_0_0_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0_0_0_0:setLayoutComponentEnabled(true)
Button_3_0_0_0_0:setName("Button_3_0_0_0_0")
Button_3_0_0_0_0:setTag(39)
Button_3_0_0_0_0:setCascadeColorEnabled(true)
Button_3_0_0_0_0:setCascadeOpacityEnabled(true)
Button_3_0_0_0_0:setPosition(363.0961, 43.5022)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0_0_0_0)
layout:setPositionPercentX(0.2837)
layout:setPositionPercentY(0.0604)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(331.0961)
layout:setRightMargin(884.9039)
layout:setTopMargin(644.4979)
layout:setBottomMargin(11.5022)
Layer:addChild(Button_3_0_0_0_0)

--Create Button_3_0_0_0_0_0
local Button_3_0_0_0_0_0 = ccui.Button:create()
Button_3_0_0_0_0_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0_0:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0_0_0_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0_0_0_0_0:setTitleFontSize(14)
Button_3_0_0_0_0_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0_0_0_0_0:setScale9Enabled(true)
Button_3_0_0_0_0_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0_0_0_0_0:setLayoutComponentEnabled(true)
Button_3_0_0_0_0_0:setName("Button_3_0_0_0_0_0")
Button_3_0_0_0_0_0:setTag(40)
Button_3_0_0_0_0_0:setCascadeColorEnabled(true)
Button_3_0_0_0_0_0:setCascadeOpacityEnabled(true)
Button_3_0_0_0_0_0:setPosition(482.0536, 54.0936)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0_0_0_0_0)
layout:setPositionPercentX(0.3766)
layout:setPositionPercentY(0.0751)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(450.0536)
layout:setRightMargin(765.9464)
layout:setTopMargin(633.9064)
layout:setBottomMargin(22.0936)
Layer:addChild(Button_3_0_0_0_0_0)

--Create Button_3_0_0_0_0_0_0
local Button_3_0_0_0_0_0_0 = ccui.Button:create()
Button_3_0_0_0_0_0_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0_0_0:loadTextureNormal("DragMapButton.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("SheetEditor.plist")
Button_3_0_0_0_0_0_0:loadTexturePressed("DragMapButtonSelected.png",1)
Button_3_0_0_0_0_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_3_0_0_0_0_0_0:setTitleFontSize(14)
Button_3_0_0_0_0_0_0:setTitleColor(cc.c3b(65, 65, 70))
Button_3_0_0_0_0_0_0:setScale9Enabled(true)
Button_3_0_0_0_0_0_0:setCapInsets(cc.rect(5,5,30,30))
Button_3_0_0_0_0_0_0:setLayoutComponentEnabled(true)
Button_3_0_0_0_0_0_0:setName("Button_3_0_0_0_0_0_0")
Button_3_0_0_0_0_0_0:setTag(41)
Button_3_0_0_0_0_0_0:setCascadeColorEnabled(true)
Button_3_0_0_0_0_0_0:setCascadeOpacityEnabled(true)
Button_3_0_0_0_0_0_0:setPosition(588.4690, 46.4925)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3_0_0_0_0_0_0)
layout:setPositionPercentX(0.4597)
layout:setPositionPercentY(0.0646)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0889)
layout:setSize(cc.size(64.0000, 64.0000))
layout:setLeftMargin(556.4690)
layout:setRightMargin(659.5310)
layout:setTopMargin(641.5075)
layout:setBottomMargin(14.4925)
Layer:addChild(Button_3_0_0_0_0_0_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

